- take the best performing model and do some clustering to identify the races it performs well on.

In [1]:
import sys
sys.path.append('../src')

import mlflow
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression # type: ignore
from sklearn.model_selection import GridSearchCV # type: ignore

import pandas as pd
import numpy as np
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.metrics import classification_report
from imblearn.over_sampling import RandomOverSampler, SMOTE
import pickle

from functions import *

from data_cleaning import DataCleaning

import os

pd.set_option('display.max_columns', None)

In [2]:
data = pd.read_csv('../data/turf.csv')
data.head()

Course Course Direction  Distance (y) Race Type Class Going   Race Date  \
0  Ascot               RH          1100      Turf     A  Good  05/10/2024   
1  Ascot               RH          1100      Turf     A  Good  05/10/2024   
2  Ascot               RH          1100      Turf     A  Good  05/10/2024   
3  Ascot               RH          1100      Turf     A  Good  05/10/2024   
4  Ascot               RH          1100      Turf     A  Good  05/10/2024   

  Race Time  Racecard No.  Draw  Draw IV  Position              Horse  DTN  \
0     13:50             1     5     1.05       6.0  Democracy Dilemma  7.0   
1     13:50             2     3     0.67       5.0       Go Athletico  6.0   
2     13:50             3     1     1.24       1.0            Rumstar  0.0   
3     13:50             4     4     1.43       2.0  Beautiful Diamond  2.0   
4     13:50             5     2     0.86       3.0          Miaharris  0.3   

         DTW          Jockey  Jockey Claim            Trainer  Age  \
0  16.049999   Jamie Spencer             0      Robert Cowell    4   
1   9.050000          D Egan             0  Adrian McGuinness    6   
2   0.000000   Hector Crouch             0   Jonathan Portman    4   
3   2.000000    Clifford Lee             0          K R Burke    3   
4   2.300000  Daniel Tudhope             0       Owen Burrows    3   

   Weight (pounds)  Penalty  Weight Rank  DSLR Equip Sex Abbrev  Favourite  \
0              132        0            1  14.0   NaN          g        NaN   
1              129        0            2   6.0   NaN          g        NaN   
2              129        0            2  21.0   NaN          g        NaN   
3              127        0            4  20.0   NaN          f        3.0   
4              124        0            5  48.0   NaN          f        NaN   

   BF Decimal SP  Won (1=Won, 0=Lost)  Place (1=Placed, 0=UnPlaced)  \
0           6.79                    0                             0   
1          10.38                    0                             0   
2           7.08                    1                             0   
3           4.05                    0                             1   
4          13.50                    0                             0   

   PRC Average  PRC Last Run  PRC 2nd Last Run  PRC 3rd Last Run Pace Abbrev  \
0           94            90                97                94           L   
1           88            84                86                94           P   
2           87            93                76                91           P   
3           95            91                96                97           P   
4           88            88                85                92           H   

   Pace Rating  Pace Rating Rank   OR  OR Rank Tissue Odds Text  \
0           12                 1  106        1              9/2   
1            4                 3  104        2              9/2   
2            4                 3  101        5             14/1   
3            6                 2  104        2              7/2   
4            4                 3   99        6             17/2   

   Tissue Odds Decimal  Tissue Rating  Tissue Rating Rank  TIS+PFR  PFR  \
0                  5.5             36                   3       80   44   
1                  5.5             35                   4       64   29   
2                 15.0             13                   6       32   19   
3                  4.5             44                   2       90   46   
4                  9.5             21                   5       60   39   

   PFR Rank  Main  Main Rank  Main Stats  Main+Stats Rank  Stats  Stats Rank  \
0         3   334          3         663                3    329           4   
1         5   317          4         635                5    318           5   
2         6   281          6         579                6    298           6   
3         2   342          2         683                2    341           3   
4         4   288 

In [3]:
bins = [800, 1000, 1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600,
        2800, 3000, 3200, 3400, 3600, 3800, 4000]

data['distance_bucket'] = pd.cut(data['Distance (y)'], bins = bins,
                               labels=['800-1000', '1000-1200', '1200-1400', '1400-1600', '1600-1800', '1800-2000',
                                       '2000-2200', '2200-2400', '2400-2600', '2600-2800', '2800-3000',
                                       '3000-3200', '3200-3400', '3400-3600', '3600-3800', '3800-4000'])

Create a df with 5 independent features and 'Won (1=Won, 0=Lost)' as the dependent variable

In [4]:
df = data[['Race Time', 'Course', 'Horse', 'Distance (y)','distance_bucket', 'Won (1=Won, 0=Lost)', 'BF Decimal SP', 'Weight (pounds)', 
           'PFR', 'User Rating 1 LTO', 'Draw IV']]

In [5]:
df.head(5)

Race Time Course              Horse  Distance (y) distance_bucket  \
0     13:50  Ascot  Democracy Dilemma          1100       1000-1200   
1     13:50  Ascot       Go Athletico          1100       1000-1200   
2     13:50  Ascot            Rumstar          1100       1000-1200   
3     13:50  Ascot  Beautiful Diamond          1100       1000-1200   
4     13:50  Ascot          Miaharris          1100       1000-1200   

   Won (1=Won, 0=Lost)  BF Decimal SP  Weight (pounds)  PFR  \
0                    0           6.79              132   44   
1                    0          10.38              129   29   
2                    1           7.08              129   19   
3                    0           4.05              127   46   
4                    0          13.50              124   39   

   User Rating 1 LTO  Draw IV  
0              147.0     1.05  
1               93.0     0.67  
2               29.0     1.24  
3               31.0     1.43  
4              113.0     0.86

In [6]:
df['BF Decimal SP1'] = df['BF Decimal SP']

/var/folders/nv/lzp9ffbj6cs24kjrpcj0q1ym0000gn/T/ipykernel_70580/1127700590.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['BF Decimal SP1'] = df['BF Decimal SP']


In [7]:
cleaned_df = DataCleaning.replace_nan(df, ['BF Decimal SP', 'Weight (pounds)', 
           'PFR', 'User Rating 1 LTO', 'Draw IV'])

In [8]:
normalized_df = DataCleaning.normalize_columns(cleaned_df, ['BF Decimal SP', 'Weight (pounds)', 
           'PFR', 'User Rating 1 LTO','Draw IV'])

normalized_df.head(5)

Race Time Course              Horse  Distance (y) distance_bucket  \
0     13:50  Ascot  Democracy Dilemma          1100       1000-1200   
1     13:50  Ascot       Go Athletico          1100       1000-1200   
2     13:50  Ascot            Rumstar          1100       1000-1200   
3     13:50  Ascot  Beautiful Diamond          1100       1000-1200   
4     13:50  Ascot          Miaharris          1100       1000-1200   

   Won (1=Won, 0=Lost)  BF Decimal SP  Weight (pounds)       PFR  \
0                    0       0.005796         0.409836  0.416667   
1                    0       0.009389         0.360656  0.291667   
2                    1       0.006086         0.360656  0.208333   
3                    0       0.003053         0.327869  0.433333   
4                    0       0.012513         0.278689  0.375000   

   User Rating 1 LTO   Draw IV  BF Decimal SP1  
0           0.207334  0.150000            6.79  
1           0.131171  0.095714           10.38  
2           0.040903  0.177143            7.08  
3           0.043724  0.204286            4.05  
4           0.159379  0.122857           13.50

In [9]:
train_data, test_data = DataCleaning.split_data(df = normalized_df)

X_train = train_data[['BF Decimal SP', 'Weight (pounds)', 'PFR', 'User Rating 1 LTO', 'Draw IV']]
y_train = train_data['Won (1=Won, 0=Lost)']

X_test = test_data[['BF Decimal SP', 'Weight (pounds)', 'PFR', 'User Rating 1 LTO', 'Draw IV']]
y_test = test_data['Won (1=Won, 0=Lost)']


In [10]:
# count of unique races
unique_race_count = test_data['Race Time'].nunique()

print(f'Count of unique races in the test data is {unique_race_count}')

Count of unique races in the test data is 207


# Use grid search to idenify the best hyperparameters for the model

In [11]:
est_data_ = test_data.copy()

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

grid_search = GridSearchCV(RandomForestClassifier(random_state=42), param_grid, cv=5, scoring='f1', n_jobs=-1)
grid_search.fit(X_train, y_train)
best_model = grid_search.best_estimator_

y_pred1 = best_model.predict(X_test)
est_data_['model_preds'] = y_pred1
print_metrics(y_test, y_pred1)


Confusion Matrix: 
[[11388   137]
 [ 1340   135]]
Accuracy: 0.8863846153846154
Precision: 0.4963235294117647
Recall: 0.09152542372881356
F1 score: 0.15455065827132228
ROC AUC score: 0.5398191109967279


# Run the data through a random forest classifier.

In [12]:
test_data1 = test_data.copy()

# Instantiate and train the Random Forest classifier
params = {
    'n_estimators' : 100,
    'random_state' : 42
}
with mlflow.start_run():
    # Log the hyperparameters
    mlflow.log_params(params)

    rf_classifier = RandomForestClassifier(**params)
    rf_classifier.fit(X_train, y_train)

    # Log the trained model
    mlflow.sklearn.log_model(rf_classifier, "random_forest_model")

    # Make predictions on the test set
    y_pred = rf_classifier.predict(X_test)

    test_data1['model_preds'] = y_pred

    # Evaluate the model
    # use the eval method
    print_metrics(y_test, y_pred)
    mlflow.end_run()

with open('../models/base_model.pkl', 'wb') as f:
    pickle.dump(rf_classifier, f)

2025/09/05 14:06:57 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/09/05 14:07:00 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.



Confusion Matrix: 
[[11388   137]
 [ 1340   135]]
Accuracy: 0.8863846153846154
Precision: 0.4963235294117647
Recall: 0.09152542372881356
F1 score: 0.15455065827132228
ROC AUC score: 0.5398191109967279


In [13]:
profit_calculation(test_data1)

Total number of bets: 272
Total return from betting £1.00 on each prediction where model_preds == 1: £-4.49
Return per pound invested: £-0.02
Model accuracy: 49.63%


In [14]:
test_data2 = test_data.copy()


# Example class weights for an imbalanced dataset
class_weights = {0: 1, 1: 5}

# Initialize and fit the RandomForest model
model = RandomForestClassifier(class_weight=class_weights, max_depth=10, min_samples_leaf=5)
model.fit(X_train, y_train)

# Predictions and evaluation
y_pred1 = model.predict(X_test)

test_data2['model_preds'] = y_pred1

print_metrics(y_test, y_pred1)



Confusion Matrix: 
[[9750 1775]
 [ 754  721]]
Accuracy: 0.8054615384615385
Precision: 0.28886217948717946
Recall: 0.4888135593220339
F1 score: 0.36313271216318305
ROC AUC score: 0.667400272068826


In [15]:
profit_calculation(test_data2)

Total number of bets: 2496
Total return from betting £1.00 on each prediction where model_preds == 1: £-14.47
Return per pound invested: £-0.01
Model accuracy: 28.89%


# Instantiate and train the Gradient Boosting classifier

In [16]:
test_data_gbm = test_data.copy()

# Instantiate the Gradient Boosting Classifier
gbm = GradientBoostingClassifier()

param_grid = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Instantiate the GridSearchCV object
grid_search = GridSearchCV(estimator=gbm, param_grid=param_grid, cv=5, scoring='f1', n_jobs=-1, verbose=2)

# Fit Grid Search
grid_search.fit(X_train, y_train)

# Get the best parameters
best_params = grid_search.best_params_
print(f"Best parameters: {best_params}")

# Get the best model
best_model = grid_search.best_estimator_

# Evaluate the best model on the test set
y_pred_gbm = best_model.predict(X_test)

test_data_gbm['model_preds'] = y_pred_gbm

print_metrics(y_test, y_pred_gbm)


Fitting 5 folds for each of 243 candidates, totalling 1215 fits
[CV] END learning_rate=0.01, max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=50; total time=   2.0s
[CV] END learning_rate=0.01, max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=50; total time=   2.0s
[CV] END learning_rate=0.01, max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=50; total time=   2.1s
[CV] END learning_rate=0.01, max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=50; total time=   2.1s
[CV] END learning_rate=0.01, max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=50; total time=   2.1s
[CV] END learning_rate=0.01, max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   4.0s
[CV] END learning_rate=0.01, max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   4.0s
[CV] END learning_rate=0.01, max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=100; 

In [17]:
profit_calculation(test_data_gbm)

Total number of bets: 382
Total return from betting £1.00 on each prediction where model_preds == 1: £-16.73
Return per pound invested: £-0.04
Model accuracy: 42.93%


In [18]:
# Instantiate and train the Gradient Boosting classifier

test_data3 = test_data.copy()

gb_classifier = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred_gb = gb_classifier.predict(X_test)

test_data3['model_preds'] = y_pred_gb

print_metrics(y_test, y_pred_gb)


Confusion Matrix: 
[[11454    71]
 [ 1371   104]]
Accuracy: 0.8890769230769231
Precision: 0.5942857142857143
Recall: 0.07050847457627119
F1 score: 0.12606060606060607
ROC AUC score: 0.5321739769844479


In [19]:
profit_calculation(test_data3)

Total number of bets: 175
Total return from betting £1.00 on each prediction where model_preds == 1: £2.04
Return per pound invested: £0.01
Model accuracy: 59.43%


In [20]:
test_data4 = test_data.copy()

model = XGBClassifier(reg_lambda=1, reg_alpha=0)
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_xgb = model.predict(X_test)

test_data4['model_preds'] = y_pred_xgb

print_metrics(y_test, y_pred_gb)


Confusion Matrix: 
[[11454    71]
 [ 1371   104]]
Accuracy: 0.8890769230769231
Precision: 0.5942857142857143
Recall: 0.07050847457627119
F1 score: 0.12606060606060607
ROC AUC score: 0.5321739769844479


In [21]:
profit_calculation(test_data4)

Total number of bets: 247
Total return from betting £1.00 on each prediction where model_preds == 1: £-15.55
Return per pound invested: £-0.06
Model accuracy: 48.58%


# Look at utilizing Random Oversampling on the dataset. This is due to the imbalanced nature of the target column.

In [22]:
# Apply Random Oversampling
ros = RandomOverSampler(random_state=42)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

print(f"Length of  X_train: {len(X_train)}\nLength of y_train: {len(y_train)}")
print(f"\nLength of  X_resampled: {len(X_resampled)}\nLength of y_resampled: {len(y_resampled)}")

Length of  X_train: 52680
Length of y_train: 52680

Length of  X_resampled: 93520
Length of y_resampled: 93520


In [23]:
# Instantiate and train the Gradient Boosting classifier
test_data5 = test_data.copy()

gb_classifier = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb_classifier.fit(X_resampled, y_resampled)

# Make predictions on the test set
y_pred_gbx = gb_classifier.predict(X_test)

test_data5['model_preds'] = y_pred_gbx

print_metrics(y_test, y_pred_gbx)


Confusion Matrix: 
[[7749 3776]
 [ 403 1072]]
Accuracy: 0.6785384615384615
Precision: 0.22112211221122113
Recall: 0.7267796610169491
F1 score: 0.33907955084611735
ROC AUC score: 0.6995720430898195


In [24]:
profit_calculation(test_data5)

Total number of bets: 4848
Total return from betting £1.00 on each prediction where model_preds == 1: £-68.83
Return per pound invested: £-0.01
Model accuracy: 22.11%


# Try an approach using smote

In [25]:
test_data6 = test_data.copy()

smote= SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

gb_classifier = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb_classifier.fit(X_train_smote, y_train_smote)

# Make predictions on the test set
y_pred_gbs = gb_classifier.predict(X_test)

test_data6['model_preds'] = y_pred_gbs

# Evaluate the model
# use the eval method
print_metrics(y_test, y_pred)


Confusion Matrix: 
[[11388   137]
 [ 1340   135]]
Accuracy: 0.8863846153846154
Precision: 0.4963235294117647
Recall: 0.09152542372881356
F1 score: 0.15455065827132228
ROC AUC score: 0.5398191109967279


In [26]:
profit_calculation(test_data6)

Total number of bets: 4228
Total return from betting £1.00 on each prediction where model_preds == 1: £0.89
Return per pound invested: £0.00
Model accuracy: 23.27%


In [27]:
test_data7 = test_data.copy()

X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

rf_classifier = RandomForestClassifier(**params)
rf_classifier.fit(X_train_smote, y_train_smote)

# Make predictions on the test set
y_pred = rf_classifier.predict(X_test)

test_data7['model_preds'] = y_pred

# Evaluate the model
# use the eval method
print_metrics(y_test, y_pred)


Confusion Matrix: 
[[10160  1365]
 [  981   494]]
Accuracy: 0.8195384615384615
Precision: 0.26573426573426573
Recall: 0.33491525423728813
F1 score: 0.29634073185362925
ROC AUC score: 0.6082385381815508


In [28]:
profit_calculation(test_data7)

Total number of bets: 1859
Total return from betting £1.00 on each prediction where model_preds == 1: £-63.96
Return per pound invested: £-0.03
Model accuracy: 26.57%


In [29]:
test_data8 = test_data.copy()

# Assume X_train, X_test, y_train, y_test are already defined
# Setting class_weight to 'balanced' makes the algorithm cost-sensitive
model = RandomForestClassifier(class_weight='balanced')

# Training the model
model.fit(X_train, y_train)

# Predictions
y_predx = model.predict(X_test)

test_data8['model_preds'] = y_predx

# Evaluation
print_metrics(y_test, y_predx)


Confusion Matrix: 
[[11415   110]
 [ 1372   103]]
Accuracy: 0.886
Precision: 0.4835680751173709
Recall: 0.06983050847457627
F1 score: 0.12203791469194313
ROC AUC score: 0.5301430199639693


In [30]:
profit_calculation(test_data8)

Total number of bets: 213
Total return from betting £1.00 on each prediction where model_preds == 1: £-13.47
Return per pound invested: £-0.06
Model accuracy: 48.36%


In [31]:
test_data9 = test_data.copy()

# Define cost matrix
C_FN = 5  # Cost of false negative
C_FP = 1  # Cost of false positive

# Assuming y_train has values 0 and 1
weights = np.ones(y_train.shape[0])
weights[y_train == 1] = C_FN
weights[y_train == 0] = C_FP

# Train logistic regression model with custom weights
model = LogisticRegression()
model.fit(X_train, y_train, sample_weight=weights)

# Predictions
y_predz = model.predict(X_test)

test_data9['model_preds'] = y_predz

# Evaluation
print_metrics(y_test, y_predz)



Confusion Matrix: 
[[9629 1896]
 [ 847  628]]
Accuracy: 0.789
Precision: 0.24881141045958796
Recall: 0.4257627118644068
F1 score: 0.31407851962990746
ROC AUC score: 0.6306253906393617


In [32]:
profit_calculation(test_data9)

Total number of bets: 2524
Total return from betting £1.00 on each prediction where model_preds == 1: £-30.01
Return per pound invested: £-0.01
Model accuracy: 24.88%


# Try a tensorflow model

In [33]:
test_data10 = test_data.copy()

model = Sequential([
    Dense(64, activation='relu', input_shape = (X_train.shape[1], )), # input layer
    Dense(32, activation='relu'), # hidden layer
    Dense(1, activation='sigmoid') # output layer for binary classification
])

# compile the model
model.compile(optimizer='adam',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

# Get model predictions as probabilities
predictions = model.predict(X_test)

# Convert probabilities to binary outcomes (0 or 1)
predicted_classes = (predictions > 0.5).astype("int32").flatten()

test_data10['model_preds'] = predicted_classes
test_data10['probability'] = predictions

# Evaluation
print_metrics(y_test, predicted_classes)

NameError: name 'Sequential' is not defined

In [ ]:
profit_calculation(test_data10)

Total number of bets: 16
Total return from betting £1.00 on each prediction where model_preds == 1: £-5.00
Return per pound invested: £-0.31
Model accuracy: 68.75%


In [ ]:
test_data10.head(5)

Race Time     Course             Horse  Distance (y)  \
72  01/05/2021 15:40:00  Newmarket      Battleground          1760   
73  01/05/2021 15:40:00  Newmarket           Chindit          1760   
74  01/05/2021 15:40:00  Newmarket         Devilwala          1760   
75  01/05/2021 15:40:00  Newmarket  Legion Of Honour          1760   
76  01/05/2021 15:40:00  Newmarket        Lucky Vega          1760   

   distance_bucket  Won (1=Won, 0=Lost)  SP Odds Decimal   weight       PFR  \
72       1600-1800                    0            0.010  0.54902  0.520661   
73       1600-1800                    0            0.024  0.54902  0.471074   
74       1600-1800                    0            0.200  0.54902  0.181818   
75       1600-1800                    0            0.160  0.54902  0.355372   
76       1600-1800                    0            0.024  0.54902  0.438017   

    Won P/L Before  evening_morning_price  SP Odds Decimal1  model_preds  \
72        0.141670               0.129031                 6            0   
73        0.172753               0.077203                13            0   
74        0.127886               0.054744               101            0   
75        0.124938               0.068951                81            0   
76        0.149201               0.064826                13            0   

    probability  
72     0.162927  
73     0.059246  
74     0.002369  
75     0.002589  
76     0.060850

In [ ]:
test_data11 = test_data.copy()

# Train the model
history = model.fit(X_resampled, y_resampled, epochs=10, batch_size=32, validation_data=(X_test, y_test))

# Get model predictions as probabilities
predictions1 = model.predict(X_test)

# Convert probabilities to binary outcomes (0 or 1)
predicted_classes1 = (predictions > 0.5).astype("int32").flatten()

test_data11['model_preds'] = predicted_classes1
test_data11['probability'] = predictions1

# Evaluation
print_metrics(y_test, predicted_classes1)

TypeError: LogisticRegression.fit() got an unexpected keyword argument 'epochs'

In [ ]:
profit_calculation(test_data11)

Total number of bets: 16
Total return from betting £1.00 on each prediction where model_preds == 1: £-5.00
Return per pound invested: £-0.31
Model accuracy: 68.75%


# Play around ith the logistic regression model as that is showing the best profit
- finetune it by playing with penalties and subsets of the data
    - distance buckets, classes
- also try running balanced datasets throught the model.

In [ ]:
test_data9 = test_data.copy()

# Define cost matrix
C_FN = 5  # Cost of false negative
C_FP = 1  # Cost of false positive

# Assuming y_train has values 0 and 1
weights = np.ones(y_train.shape[0])
weights[y_train == 1] = C_FN
weights[y_train == 0] = C_FP

# Train logistic regression model with custom weights
model = LogisticRegression()
model.fit(X_train, y_train, sample_weight=weights)

# Predictions
y_predz = model.predict(X_test)

test_data9['model_preds'] = y_predz

# Evaluation
print_metrics(y_test, y_predz)

profit_calculation(test_data9)


Confusion Matrix: 
[[9712 1813]
 [ 831  644]]
Accuracy: 0.7966153846153846
Precision: 0.2621082621082621
Recall: 0.4366101694915254
F1 score: 0.3275686673448627
ROC AUC score: 0.6396499871318798
Total number of bets: 2457
Total return from betting £1.00 on each prediction where model_preds == 1: £62.08
Return per pound invested: £0.03
Model accuracy: 26.21%


# firstly lets try the smote dataset

In [ ]:
test_data_smote = test_data.copy()

smote= SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

# Define cost matrix
C_FN = 5  # Cost of false negative
C_FP = 1  # Cost of false positive

# Assuming y_train has values 0 and 1
weights = np.ones(y_train_smote.shape[0])
weights[y_train_smote == 1] = C_FN
weights[y_train_smote == 0] = C_FP

# Train logistic regression model with custom weights
model = LogisticRegression()
model.fit(X_train_smote, y_train_smote, sample_weight=weights)

# Predictions
y_pred_smote = model.predict(X_test)

test_data_smote['model_preds'] = y_pred_smote

# Evaluation
print_metrics(y_test, y_pred_smote)

profit_calculation(test_data_smote)


Confusion Matrix: 
[[2062 9463]
 [  31 1444]]
Accuracy: 0.2696923076923077
Precision: 0.1323920418080132
Recall: 0.9789830508474576
F1 score: 0.23324180261670163
ROC AUC score: 0.5789492260744881
Total number of bets: 10907
Total return from betting £1.00 on each prediction where model_preds == 1: £79.82
Return per pound invested: £0.01
Model accuracy: 13.24%


# try random oversampling

In [ ]:
# Apply Random Oversampling
ros = RandomOverSampler(random_state=42)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

test_data_ros = test_data.copy()

# Define cost matrix
C_FN = 5  # Cost of false negative
C_FP = 1  # Cost of false positive

# Assuming y_train has values 0 and 1
weights = np.ones(y_resampled.shape[0])
weights[y_resampled == 1] = C_FN
weights[y_resampled == 0] = C_FP

# Train logistic regression model with custom weights
model = LogisticRegression()
model.fit(X_resampled, y_resampled, sample_weight=weights)

# Predictions
y_pred_ros = model.predict(X_test)

test_data_ros['model_preds'] = y_pred_ros

# Evaluation
print_metrics(y_test, y_pred_ros)

profit_calculation(test_data_ros)


Confusion Matrix: 
[[1835 9690]
 [  27 1448]]
Accuracy: 0.25253846153846154
Precision: 0.13000538696354821
Recall: 0.9816949152542372
F1 score: 0.22960437643700943
ROC AUC score: 0.5704570020956652
Total number of bets: 11138
Total return from betting £1.00 on each prediction where model_preds == 1: £50.89
Return per pound invested: £0.00
Model accuracy: 13.00%


# play around with some different penalties

In [ ]:
%%script false --no-raise-error

# Copy test data
test_data91 = test_data.copy()

# Define grid of penalty values to test
C_FN_values = range(1,30)  # Range of false negative penalties
C_FP_values = range(1,30)  # Range of false positive penalties

# Initialize variables to store the best results
best_C_FN = None
best_C_FP = None
best_profit = -np.inf  # Start with negative infinity to ensure any positive profit is better

# Iterate over each combination of C_FN and C_FP
for C_FN in C_FN_values:
    for C_FP in C_FP_values:
        # Assign weights based on the current C_FN and C_FP
        weights = np.ones(y_train.shape[0])
        weights[y_train == 1] = C_FN
        weights[y_train == 0] = C_FP

        # Train the logistic regression model
        model = LogisticRegression()
        model.fit(X_train, y_train, sample_weight=weights)

        # Make predictions on the test data
        y_predz = model.predict(X_test)

        # Add predictions to the test data
        test_data91['model_preds'] = y_predz

        # Calculate the profit or loss (assuming profit_calculation function is defined)
        profit_calculation(test_data91)
        

        # Optional: Print progress (for larger grids)
        print(f"C_FN: {C_FN}, C_FP: {C_FP}\n")


# this is the model moving forward

In [ ]:
test_data1 = test_data.copy()

# Instantiate and train the Random Forest classifier
params = {
    'n_estimators' : 100,
    'random_state' : 42
}
with mlflow.start_run():
    # Log the hyperparameters
    mlflow.log_params(params)

    rf_classifier = RandomForestClassifier(**params)
    rf_classifier.fit(X_train, y_train)

    # Log the trained model
    mlflow.sklearn.log_model(rf_classifier, "random_forest_model")

    # Make predictions on the test set
    y_pred = rf_classifier.predict(X_test)

    test_data1['model_preds'] = y_pred

    # Evaluate the model
    # use the eval method
    print_metrics(y_test, y_pred)
    mlflow.end_run()

with open('../models/base_model.pkl', 'wb') as f:
    pickle.dump(rf_classifier, f)

2025/09/05 13:51:10 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/09/05 13:51:12 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.



Confusion Matrix: 
[[11339   186]
 [ 1345   130]]
Accuracy: 0.8822307692307693
Precision: 0.41139240506329117
Recall: 0.08813559322033898
F1 score: 0.14517029592406477
ROC AUC score: 0.5359983822934666


In [ ]:
test_data_best = test_data.copy()

# Define cost matrix
# we are assigning a greater cost to false negatives.
C_FN = 6  # Cost of false negative
C_FP = 1  # Cost of false positive

# Assuming y_train has values 0 and 1

# creating a numpy array of one's where the length of the array == len(y_train)
# initially every sampple in the dataset is given a value of one
weights = np.ones(y_train.shape[0])

# here we are modifying the weights of all the samples in the training set that belong to class 1
# therefore the weights for samples where the label is 1 are updated to C_FN
weights[y_train == 1] = C_FN

# here we are modifying the weights of all the samples in the training set that belong to class 0
# therefore the weights for samples where the label is 1 are updated to C_FP
weights[y_train == 0] = C_FP

# Train logistic regression model with custom weights
model = LogisticRegression()
model.fit(X_train, y_train, sample_weight=weights)

# Save the model to a file using pickle
with open('../models/logistic_regression_model.pkl', 'wb') as f:
    pickle.dump(model, f)

test_data_best['model_preds'] = y_predz

# Evaluation
print_metrics(y_test, y_predz)
print()
profit_calculation(test_data_best, stake = 1)



Confusion Matrix: 
[[9712 1813]
 [ 831  644]]
Accuracy: 0.7966153846153846
Precision: 0.2621082621082621
Recall: 0.4366101694915254
F1 score: 0.3275686673448627
ROC AUC score: 0.6396499871318798

Total number of bets: 2457
Total return from betting £1.00 on each prediction where model_preds == 1: £62.08
Return per pound invested: £0.03
Model accuracy: 26.21%
